0.14.13 - Push notification 1341
ChildMindInstitute/mindlogger-app pull request #1347
Opened 2020-11-09 04:04 UTC by Matchdev120

Resolved #1345 

Upgrade ```PushNotificationiOS``` to 1.7.1

2020-11-09 05:05 UTC, ngonzalvez approved these changes

2020-11-11 02:15 UTC, devbtech commented
@Matchdev120 It's being failed in Bitrise. Attached error log in Bitrise.
![image](https://user-images.githubusercontent.com/52746858/98757119-ceb6ff80-2399-11eb-94ea-59f11d9674b9.png)

2020-11-11 02:18 UTC, devbtech requested changes
@Matchdev120 It's being failed in Bitrise. Attached error log in Bitrise.

2020-11-16 04:19 UTC, devbtech approved these changes

2020-11-16 04:21 UTC, merged