Watermark and large text #368 #391
ChildMindInstitute/mindlogger-app pull request #1823
Opened 2021-06-29 11:56 UTC by Matchdev120

#368 and #391

2021-07-22 00:16 UTC, devbtech requested changes

2021-07-22 00:16 UTC, devbtech commented on app/state/applets/applets.thunks.js
> +<<<<<<< HEAD
syntax error @Matchdev120

2021-07-22 13:05 UTC, Matchdev120 commented on app/state/applets/applets.thunks.js
> +<<<<<<< HEAD
I'll fix the merge conflict.

2021-07-26 03:23 UTC, devbtech approved these changes

2021-07-30 04:12 UTC, merged